<?php

namespace DoctrineORMModule\Proxy\__CG__\Pc_help\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Maquina extends \Pc_help\Entity\Maquina implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'cod_maq', 'cliente', 'problema', 'tipo', 'marca', 'modelo', 'cor', 'processador', 'tela', 'grafico', 'ram', 'hd', 'obs');
        }

        return array('__isInitialized__', 'cod_maq', 'cliente', 'problema', 'tipo', 'marca', 'modelo', 'cor', 'processador', 'tela', 'grafico', 'ram', 'hd', 'obs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Maquina $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodMaq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodMaq', array());

        return parent::getCodMaq();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodMaq($cod_maq)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodMaq', array($cod_maq));

        return parent::setCodMaq($cod_maq);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($marca));

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', array());

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', array($modelo));

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCor', array());

        return parent::getCor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCor($cor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCor', array($cor));

        return parent::setCor($cor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessador', array());

        return parent::getProcessador();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessador($processador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessador', array($processador));

        return parent::setProcessador($processador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTela', array());

        return parent::getTela();
    }

    /**
     * {@inheritDoc}
     */
    public function setTela($tela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTela', array($tela));

        return parent::setTela($tela);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrafico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrafico', array());

        return parent::getGrafico();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrafico($grafico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrafico', array($grafico));

        return parent::setGrafico($grafico);
    }

    /**
     * {@inheritDoc}
     */
    public function getRam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRam', array());

        return parent::getRam();
    }

    /**
     * {@inheritDoc}
     */
    public function setRam($ram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRam', array($ram));

        return parent::setRam($ram);
    }

    /**
     * {@inheritDoc}
     */
    public function getHd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHd', array());

        return parent::getHd();
    }

    /**
     * {@inheritDoc}
     */
    public function setHd($hd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHd', array($hd));

        return parent::setHd($hd);
    }

    /**
     * {@inheritDoc}
     */
    public function getObs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObs', array());

        return parent::getObs();
    }

    /**
     * {@inheritDoc}
     */
    public function setObs($obs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObs', array($obs));

        return parent::setObs($obs);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblema', array());

        return parent::getProblema();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblema($problema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblema', array($problema));

        return parent::setProblema($problema);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
