<h3> Cadastrar Máquina</h3>


<br />

<div class="container">

    <div class="col-lg-2">

    </div>

    <div class="container">

        <div class="col-lg-10">

            <?php
            $form = $this->form;

            $form->setAttribute('action', $this->url('pc_helpAdmin',array('controller'=>'maquina','action'=>'new')));

            $form->prepare();

            echo $this->form($form,null); ?>
        </div>



    </div>

    <?php var_dump($a) ?>