<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Regis Byte'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
          <div class='navbar navbar-inverse navbar-fixed-top'>
      <div class='container'>
        <a href='/' class='navbar-brand'>Regis Byte</a>

        <ul class='nav navbar-nav navbar-right'>
          <li><a href='tickets.html'>Cliente</a></li>
          <li><a href='stations.html'>Stations</a></li>
          <li><a href='about.html'>About</a></li>
        </ul>
      </div>
    </div> <!-- Fim do menu principal -->

          <div class="col-md-1">
          
          <?php
                $form = $this->frmcliente;
                $form->setAttribute('action', $this->url('pc_helpAdmin',array('controller'=>'Clientes','action'=>'search')));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('cpf'));
                echo $this->formSubmit($form->get('submit'))."<br /> <br />";
                echo $this->form()->closeTag();
                ?>
                
<div class="btn-group btn-group-vertical">
                  <a href="<?php echo $this->url('pc_helpAdmin',array('controller'=>'Clientes','action'=>'new')); ?>" class="btn btn-success" role="button">Cadastar Cliente</a></br></br>
                  <a href="<?php echo $this->url('pc_helpAdmin',array('controller'=>'Clientes','action'=>'new')); ?>" class="btn btn-success" role="button">Problemas Solucionados    </a></br></br>
                  <a href="#" class="btn btn-success" role="button">Controle Financeiro       </a></br></br>
                  <a href="#" class="btn btn-success" role="button">Controle de estoque</a></br></br>
                  <a href="#" class="btn btn-success" role="button">Orçamento</a></br></br>
                  <a href="<?php echo $this->url('pc_helpAdmin',array('controller'=>'problema','action'=>'list')); ?>" class="btn btn-success" role="button">Controle de Problemas</a></br></br>

              </div>

</div>


<div class="col-md-10">
   
<?php echo $this->content; 
            
            
            ?>

</div>
          
          
         
            

         
            
           
        
            
        <?php echo $this->inlineScript() ?>
    </body>
</html>
