
<h3> Atualizando OS </h3>
<br/>


<br />

<div class="container">

    <div class="col-lg-2">

    </div>

    <div class="container">

        <div class="col-lg-10">

            <?php
            $form = $this->form;

            $form->setAttribute('action', $this->url('pc_helpAdmin',array('controller'=>'problema','action'=>'edit')));

            $form->prepare();

            echo $this->form($form,null); ?>
        </div>



    </div>






